### ISSUE TITLE
Disappear horizontal mouse tracker when Invert Y Axis

### ISSUE THREAD

**Issue by AlirezaPESUT** [ScottPlot/ScottPlot#4650]
**Question:** (Hi,
I want to create a plot with a mouse tracker feature. It's straightforward using the sample code provided in the demo version. However, I also want to invert the Y-axis on this plot. When I inverted the Y-axis, the horizontal line of the mouse tracker disappeared. How can I fix this issue?)

**ScottPlot Version:** (5.0.47)

![image](https://github.com/user-attachments/assets/12efd3ff-a02d-4f7f-995c-14d5129f8fb5)
![image](https://github.com/user-attachments/assets/d7e7847c-8ead-4bf5-adb9-e2674bdb7194)

```cs
readonly ScottPlot.Plottables.Crosshair CH;
        readonly ScottPlot.Plottables.Scatter scatter;
        public frmScottPlotTest()
        {
            InitializeComponent();

            double[] x = new[] {0,1.0,2,3,4,5,6,7,8,9,10 };
            double[] y = new[] { 1, 3, 4, 8, 1, 6, 8, 11, 9.0,4,2 };

            scatter = formsPlot1.Plot.Add.ScatterLine(x, y);

            CH = formsPlot1.Plot.Add.Crosshair(0, 0);
            CH.TextColor = Colors.White;

            CH.TextBackgroundColor = CH.HorizontalLine.Color;
            formsPlot1.Refresh();
            formsPlot1.Plot.Axes.InvertY();

            formsPlot1.MouseMove += (s, e) =>
            {
                Pixel mousePixel = new(e.X, e.Y);
                Coordinates mouseCoordinates = formsPlot1.Plot.GetCoordinates(mousePixel);
                this.Text = $"X={mouseCoordinates.X:N3}, Y={mouseCoordinates.Y:N3}";
                CH.Position = mouseCoordinates;
                CH.VerticalLine.Text = $"{mouseCoordinates.X:N3}";
                CH.HorizontalLine.Text = $"{mouseCoordinates.Y:N3}";
                formsPlot1.Refresh();
            };

            formsPlot1.MouseDown += (s, e) =>
            {
                Pixel mousePixel = new(e.X, e.Y);
                Coordinates mouseCoordinates = formsPlot1.Plot.GetCoordinates(mousePixel);
                Text = $"X={mouseCoordinates.X:N3}, Y={mouseCoordinates.Y:N3} (mouse down)";
            };
        }
```

**Comment by swharden** [comment]
Thank you for reporting this! I think this issue has been resolved in one of the newer releases, but if not, let me know and we can open this issue back up again and take a closer look together. Thanks!

**Comment by SerenniaHan** [comment]
> Thank you for reporting this! I think this issue has been resolved in one of the newer releases, but if not, let me know and we can open this issue back up again and take a closer look together. Thanks!

 Hi，@swharden
I am using ScottPlot.Wpf version 5.0.54, that I found that this issue still exists.
I tried add a crosshair and make it can be draggable and display the crosshair labels, 
but after inverting the y-axis, the crosshair's label is updated properly but the horizontal line is not rendered.
If y-axis is not inverted, everything goes well.

I'm hoping for some advice. Thanks!
